### ISSUE TITLE
Not Found: /folder/7909375238_n.jpg

### ISSUE THREAD

**Issue by gookenhaim** [raagin/django-streamfield#14]
Hello! Thanks for this amazing package. I would like to use it for my existing app but this message appears
when I click on post detail page after successfully saving post in admin:
Not Found: /folder/7909375238_n.jpg

I can see my file is saved well in project root's "folder" directory but I don't know why it can't load the image.

Thanks for your help in advance.

**Comment by raagin** [comment]
Are you sure that problem is exists only inside the streamfield module?
Did you try same field outside of this module?
Also, you can show some code, that you use. Maybe we could find a problem
