### ISSUE TITLE
[Question] Compatibility

### ISSUE THREAD

**Issue by lorddaedra** [raagin/django-streamfield#21]
Can I use this app together with django-polymorphic app, is it compatible? 
Docs: https://django-polymorphic.readthedocs.io/en/stable/index.html 
Code: https://github.com/django-polymorphic/django-polymorphic

I have polymorphic-based section models. I would like to attach streamfield to all of them (with different set of available blocks per section type). So user may create section and add some blocks there.

Suggestion also: move all code inside of `StreamBlocksAdmin(admin.ModelAdmin)` to `StreamBlocksAdminMixin(object)` and add `StreamBlocksAdmin(StreamBlocksAdminMixin, admin.ModelAdmin)`.

**Comment by raagin** [comment]
Hi. Sorry, was a busy. 
django-polymorphic:
I will check it and answer later. 
Suggestion:
I think you right it can be restructured.

**Comment by raagin** [comment]
I made your suggestion with the admin mixin. Try the new release. 
About django-polymorphic - sorry, I didn’t dive into the topic
