### ISSUE TITLE
Bug with STREAMFIELD_SHOW_ADMIN_HELP_TEXT

### ISSUE THREAD

**Issue by XFaost** [raagin/django-streamfield#27]
When 
`STREAMFIELD_SHOW_ADMIN_HELP_TEXT = False`

I see the next image:
![image](https://user-images.githubusercontent.com/46850601/210673210-3bb7e2df-8274-4bd2-81a5-94f789ac6f19.png)

The reason is the label:
![image](https://user-images.githubusercontent.com/46850601/210673276-060f2b48-4db9-4f36-88c1-015923e648f2.png)

**Comment by raagin** [comment]
Yes. It's because of float blocks in vanilla Django Admin.
You can temporary fix it by adding css:
.streamfield_app { float: left;}
I will fix this in next release. Thank you

**Comment by raagin** [comment]
Fixed in a new release
