### ISSUE TITLE
`ValueError`: The file 'streamfield/vendor/vuedraggable.umd.min.js.map' could not be found with `ManifestStaticFilesStorage` object.

### ISSUE THREAD

**Issue by fabiocaccamo** [raagin/django-streamfield#32]
Hi, 
thank you for this great package.

The following error is raised when using `ManifestStaticFilesStorage` and running `python manage.py collectstatic`:
```python
ValueError: The file 'streamfield/vendor/vuedraggable.umd.min.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f3137437d00>.
```

The cause is that `vuedraggable.umd.min.js` contains a reference to `vuedraggable.umd.min.js.map` and django tries to solve but it doesn't find the file:
https://github.com/raagin/django-streamfield/blob/master/streamfield/static/streamfield/vendor/vuedraggable.umd.min.js

Python version: 3.8
Django version: 4.1

**Comment by raagin** [comment]
You can try the new release. There this should be fixed.

**Comment by fabiocaccamo** [comment]
@raagin I confirm this issue it's fixed, thank you!
