### ISSUE TITLE
How to create formatting panel for Streamfield? 

### ISSUE THREAD

**Issue by Deimos715** [raagin/django-streamfield#39]
Hello! Do you know how to create formatting panel for Streamfield or enable ckeditor for text formatting? I need it for RichText. Here is my code:

class About(models.Model):
    stream = StreamField(
        model_list=[
            RichText,
            ImageWithText
        ],
        popup_size=(1000, 500),
        verbose_name="Блок обо мне",
    )

**Comment by raagin** [comment]
Hi! Use standard django admin functional.

If you use django-ckeditor just change `models.TextField` to `RichTextField`
(```from ckeditor.fields import RichTextField```) in your streamblocks/models.py
[https://github.com/django-ckeditor/django-ckeditor#id6](https://github.com/django-ckeditor/django-ckeditor#id6)

Or you need to customize streamblocks/admin.py to add ckeditor widget

```
admin.site.unregister(RichText)
@admin.register(RichText)
class RichTextAdmin(StreamBlocksAdmin, admin.ModelAdmin):
     # here is your code for admin class of RichText. 
```
[https://github.com/raagin/django-streamfield#custom-admin-class-for-blocks-models](https://github.com/raagin/django-streamfield#custom-admin-class-for-blocks-models)

**Comment by Deimos715** [comment]
Hello, thank you. Do you now how to set <br> between text blocks?

**Comment by raagin** [comment]
You can use css)

**Comment by raagin** [comment]
I think I misunderstood your question.

**Comment by raagin** [comment]
I fixed the bug. Try it in a new release (2.0.8). Thank you. 
What checkbox do you mean?

**Comment by Deimos715** [comment]
Hello, I've tested it on 2.0.8 with more than one picture block, removing works correctly now, thank you.
I mean checkbox for setting <br> between blocks of different types, here is the screenshot:
![Снимок экрана от 2023-05-25 18-39-18](https://github.com/raagin/django-streamfield/assets/32176134/8d99ec4a-0d3b-4cfc-85d3-d4e893d1e1c1)

The content won't be divided visually without <br>.
You have similar margins parameter:

STREAMFIELD_BLOCK_OPTIONS = {
    "margins": {
        "label": "Margins",
        "type": "checkbox",
        "default": True
    }
}

Is this possible to create similar checkbox for <br> for giving user right to decide necessity of the tag with its help?

**Comment by raagin** [comment]
Do you want to make optional a tag <br> in your template?
You may use options as you wish. See here
[https://github.com/raagin/django-streamfield#block-options](https://github.com/raagin/django-streamfield#block-options)

**Comment by Deimos715** [comment]
Great, I'll try that, thank you very much.
