### ISSUE TITLE
Add API integration section to the docs.

### ISSUE THREAD

**Issue by fabiocaccamo** [raagin/django-streamfield#42]
Thank you for this great package!

Could you add an API integration section in the documentation?
I would like to integrate this package with `django-ninja`, but I'm getting the following error:

```python
TypeError: Object of type PageTitle is not JSON serializable
```

This is my schema:

```python
class PageSchema(Schema):
    id: int
    stream: List[dict]

    def resolve_stream(self, obj):
        return obj.stream.as_list()
```

**Comment by raagin** [comment]
Hi, thank for you feedback! 
You can get data as json by using this method: 
obj.stream.to_json()

**Comment by fabiocaccamo** [comment]
Thank you!
