### ISSUE TITLE
Error when trying to add blocks programmatically using stream.add() [AttributeError: 'list' object has no attribute 'add']

### ISSUE THREAD

**Issue by adrenaline681** [raagin/django-streamfield#44]
When following the documentation, im tryng to add a block to my page programmatically and I get the following error:

`AttributeError: 'list' object has no attribute 'add'`

This is what im doing:

```
article = Article()
new_block = Text(text='<p>Hello world</p>')
article.content.add(new_block)
article.save()
```

I'm following this documentation: https://github.com/raagin/django-streamfield#add-block-programarly

And of course the content is a StreamField:

```
class Article(models.Model):
    ...
    content = StreamField(model_list=[Text])    
```

**Comment by adrenaline681** [comment]
I run this command:
```
print(type(article._meta.get_field('content')))
print(type(article.content))
```

I get this output:
```
<class 'streamfield.fields.StreamField'>
<class 'list'>
```

I have also confirmed the Article model, does use the StreamField for the "content" field.

I tried also saving the block and the article object before trying to add the new item.

```
article = Article()
new_block = Text(text='<p>hello world</p')
new_block.save()
article.content.add(new_block)
article.save()
```
and
```
article = Article()
article.save()
new_block = Text(text='<p>hello world</p')
new_block.save()
article.content.add(new_block)
article.save()
```

But I still get the same error:
```
article.content.add(new_block)
^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
```

**Comment by raagin** [comment]
Ok. Do you have access to other attributes? For example can you render the field?
`article.content.render`

**Comment by adrenaline681** [comment]
I get this:

```
print(article.content.render)
AttributeError: 'list' object has no attribute 'render'
```

**Comment by raagin** [comment]
Ok, i got the problem.

**Comment by adrenaline681** [comment]
Thanks @raagin, this seems to work!
Would be great to include this info in the documentation.
Cheers!

**Comment by raagin** [comment]
Sure! Thank you
