### ISSUE TITLE
Orphaned/existing blocks

### ISSUE THREAD

**Issue by globophobe** [raagin/django-streamfield#5]
This is really great! 

I wonder if there is anyway to cleanup orphaned blocks, though. Deleting blocks, or the page, don't delete underlying column or text objects.  

I know it's a limitation of streamfield and nosql. However, my users are going to create hundreds/thousands of orphaned blocks, if they have the chance.

It'd also be nice to link to existing blocks.

**Comment by raagin** [comment]
Thank you, for feedback. 
About deleting: Yes, i think to make it in a next release. I just think about, how do it better and keep backward compatibility. 
Aboout link to existing blocks: Do you mean instances of the models in streamblocks module? Or from others apps?

**Comment by globophobe** [comment]
Instances of streamblocks.

**Comment by raagin** [comment]
Maybe it is good idea, but i have not met a case where it was needed. It is can be as optional feature. In that case, irreversible removal of instance also should be optional. I think most important for now to fix deleting of instances from db. In plans: Delete instance of the block when parent instance with StreamField is saved

**Comment by raagin** [comment]
Hi. You may try new release.

**Comment by globophobe** [comment]
Very nice.

**Comment by globophobe** [comment]
About linking to existing blocks. Please forget about that, my thinking was wrong. I was thinking about Wagtail's StreamField, and making something like a photo gallery.

Actually, your way is so much better. I realize I should think of your StreamBlocks as intermediate models.

```
 class Photo(models.Model):
    ...

class PhotoBlock(models.Model):
    photo = models.ForeignKey('Photo', on_delete=models.CASCADE)
```

One thing though, if I delete the block elsewhere. For example:

```
>>> from streamblocks.models import RichText
>>> RichText.objects.all()
<QuerySet [<RichText: RichText object (1)>]>
>>> RichText.objects.all().delete()
(1, {'streamblocks.RichText': 1})
```

The RichText link has a change link.

![Screenshot from 2020-02-14 10-38-02](https://user-images.githubusercontent.com/891192/74493746-4f81c180-4f16-11ea-8657-8375c9a183d0.png)

But, the object does not exist:

![Screenshot from 2020-02-14 10-38-47](https://user-images.githubusercontent.com/891192/74493797-60323780-4f16-11ea-969b-d16c031b6418.png)

In such a case, it would be nice to capture the 404, and alert the user with JavaScript, for example:

> "Text" no longer exists. Perhaps it was deleted? 

Then, delete the node from `<div id="app_stream"></div>`

**Comment by raagin** [comment]
Ok. I will think about it.
Another poroblem that If you delete entire object which contain StreamField, streamblock's instances will not be deleted.
![image](https://user-images.githubusercontent.com/5389817/74519005-ef931700-4f25-11ea-9de6-c0bb2fc09fda.png)
Maybe in future we will find the solution.
