### ISSUE TITLE
404 After deleting Stream Block inline

### ISSUE THREAD

**Issue by l0rn** [raagin/django-streamfield#7]
I'd like to report a bug:

If you created a streamblock without adding content, then deleting it again, trying to save the entity containing the streamfield, it'll still try to delete the not yet created streamblock resulting in a query like this: `http://localhost:8000/streamfield/admin-instance/absolutemodifier/-1/delete/`

That obiously results in a 404 failing the attempt to save the entity

**Comment by raagin** [comment]
You right. Of course this is a mistake. Thanx!
